default_platform(:ios)

  before_all do
	sh 'mkdir ../reports || true'
  end

platform :ios do

  lane :test do
    run_tests( scheme: "Task", code_coverage: true)
  end

  lane :lint do
    swiftlint(
	mode: :lint,
	output_file: "./test-reports/checkstyle-reports.xml",
	config_file: "fastlane/.swiftlint.yml",
	executable: "./Pods/SwiftLint/swiftlint"
    )
  end


  lane :coverage do
    slather(
	html: true,
	show: true,
	scheme: "Task",  
	proj: "Task.xcodeproj", 
	workspace: "Task.workspace"
	)
  end 
end
