default_platform(:ios)

  before_all do
	sh 'mkdir ../reports || true'
  end

platform :ios do

project = "Task.xcodeproj"
workspace = "Task.workspace"
test_target = "UnitTests"
derived_data_path = "fastlane/derived_data-path"
test_devices = ["iPhone X"]

  lane :test do
    run_tests( scheme: "Task", code_coverage: true)
  end

  lane :unit_test do
    scan(
        project: project,
        derived_data_path: derived_data_path,
        build_for_testing: true,
        devices = test_devices
    )
  end

lane : take_snaps do |options|
end
  lane :lint do
    swiftlint(
	  mode: :lint,
	  reporter: "checkstyle",
	  output_file: "./test-reports/checkstyle-reports.xml",
	  config_file: "fastlane/.swiftlint.yml",
	  executable: "./Pods/SwiftLint/swiftlint"
    )
  end


  lane :coverage do
    slather(
	  html: true,
	  show: true,
	  scheme: "Task",
	  proj: "Task.xcodeproj",
	  workspace: "Task.workspace"
	)
  end 
end
